project:
  type: book
  output-dir: docs

book:
  title: "INF511: Modern Regression I"
  subtitle: "Spring 2023"
  author: 
    - name: Joseph Mihaljevic
      affiliations:
        - name: Northern Arizona University
  site-url: https://jrmihalj.github.io/
  repo-url: https://github.com/joseph-mihaljevic/inf511-book
  repo-actions: [source, issue]
  chapters:
    - index.qmd
    - part: "Pre-requisites"
      chapters:
        - software.qmd
        - Rintro.qmd
        - prob.qmd
    - ols.qmd
    - hypothesis.qmd
    - max-lik.qmd
    - anova.qmd
    - bayesian.qmd
    - references.qmd
  appendices: 
    - syllabus.qmd
  sidebar:
    style: "floating"
    collapse-level: 1
    border: true
    search: true

crossref: 
    appendix-delim: ":"

bibliography: references.bib

format:
  html:
    theme: cosmo
    smooth-scroll: true
    code-link: true
    code-tools:
      toggle: true
    code-fold: false
    highlight-style: printing
    code-block-bg: true
    
  pdf:
    documentclass: scrreprt
    lof: true
    lot: true
    toc: true
    toc-depth: 2
    fig-cap-location: bottom
    tbl-cap-location: bottom
    geometry:
      - margin=1in
      - heightrounded
    hyperrefoptions:
      - linktoc=all
    colorlinks: true
    linkcolor: "blue"
    biblio-style: apalike
    keep-tex: true
    code-block-bg: true
    code-overflow: wrap
    code-line-numbers: true
